title:            Ardour 5
description:      An updated version of the original FLOSS manual.
reading_time:     true
words_per_minute: 120
url:              http://brunoruviaro.github.io/ardour4-tutorial

# Owner/author information
owner:
  name:           Ardour 5 Tutorial
  avatar:         ardour-icon.png
  bio:            "An updated version of the original Ardour FLOSS Manual."
  github:         brunoruviaro/ardour4-tutorial/

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-66949361-1

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
highlighter: pygments
markdown:    kramdown
plugins: [jekyll-paginate, jekyll-sitemap]

sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

include: [".htaccess"]
exclude: ["drafts", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
